version: '3'

services:
  librarian:
    build: ./librarian
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${LIBRARIAN_PORT}
      - PYTHONUNBUFFERED=1
    expose:
      - "${LIBRARIAN_PORT}"
    networks:
      - internal

  respondent:
    build: ./respondent
    depends_on:
      - librarian
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${RESPONDENT_PORT}
      - LIBRARIAN_ADDRESS=librarian:${LIBRARIAN_PORT}
      - PYTHONUNBUFFERED=1
    expose:
      - "${RESPONDENT_PORT}"
    networks:
      - bot
      - internal

  bot:
    build: ./bot
    depends_on:
      - respondent
    environment:
      - NODE_ENV=${NODE_ENV}
      - RESPONDENT_ADDRESS=respondent:${RESPONDENT_PORT}
      - PYTHONUNBUFFERED=1
    networks:
      - bot
          
networks:
  bot:
  internal: